### ISSUE TITLE
DevRecD1 - Dockerise deployment

### ISSUE THREAD

**Issue by TheMadBug** [SACGF/variantgrid#1163]
Create a docker container for VariantGrid for easier onboarding for new devs or people wishing to test the product.

Here is a docker settings file that Andrew Patto setup, note at this point it doesn't cover VEP - but we expect at a future date VEP etc can be managed via Mock Services that can be used at runtime not just during unit tests.

```
services:
  # the postgres db is used for storing variant information and various runtime info of the app
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: snpdb
      POSTGRES_PASSWORD: xxxx
      POSTGRES_USER: snpdb
    networks:
      - variantgrid-network-dev
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - variantgrid-postgres-dev:/var/lib/postgresql/data

  redis:
    image: redis:latest
    command: redis-server
    networks:
      - variantgrid-network-dev
    volumes:
      - redis-dev:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    expose:
      - 6379
#
#  rabbitmq:
#    image: rabbitmq:latest
#    networks:
#      - variantgrid-network-dev
#    ports:
#      - "5672:5672"
#    expose:
#      - 5672

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  redis-dev:
  redis-config:
  variantgrid-postgres-dev:

networks:
  variantgrid-network-dev:
    driver: bridge
```
